name: print hello

on: [push, pull_request]

jobs:
  build_wheels:
    name: Check on ${{ matrix.os }}
    env:
      BOOST_PATH: $GITHUB_WORKSPACE
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Cancel previous runs on the same branch
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Set the value
        id: step_one
        run: |
          echo "workspace=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Echo env
        run: echo $GITHUB_WORKSPACE

      - name: Echo env2
        run: echo ${{ env.workspace }}

      - uses: actions/setup-python@v2
        name: Install Python
        id: python-installer
        with:
          python-version: '3.8'

#      - name: Chown for boost
#        run: |
#          sudo chown -R $USER:$USER ${{ env.BOOST_PATH }}/include/
#          sudo chown -R $USER:$USER ${{ env.BOOST_PATH }}/lib/

      - name: ls
        run: ls -la
      - name: python version
        run: echo ${{ steps.python-installer.outputs.python-version }} 

      - name: Cache boost
        id: cache-boost
        uses: actions/cache@v2
        with:
          path: |
            $GITHUB_WORKSPACE
#            ${{ env.BOOST_PATH }}/include/boost
#            ${{ env.BOOST_PATH }}/lib/cmake/boost_*
#            ${{ env.BOOST_PATH }}/lib/libboost_*
#            ${{ env.BOOST_PATH }}/lib/cmake/Boost*
          key: ${{ runner.os }}-boost-more-cache3-${{ env.workspace }}

      - name: Pre-install boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          wget -nv -O boost_1_76_0.tar.gz https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz &&
          tar xzf boost_1_76_0.tar.gz -C ~/ && cd ~/boost_1_76_0/ &&
          ./bootstrap.sh --with-python=/usr/bin/python3.8 --with-python-version=3.8 --prefix=${{ env.workspace }} &&
          ./b2 -j `nproc` &&  sudo ./b2 install -j `nproc` && ls project-config.jam

      - name: cmake and build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . -- -j 6 -DBOOST_ROOT=${{ env.workspace }}
          cd ..
          python3 -m venv .venv
          . .venv/bin/activate
          pip3 install .
          pwd
          python3 ./test/test.py

