name: print hello

on: [push, pull_request]

jobs:
  build_wheels:
    name: Check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Cancel previous runs on the same branch
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        name: Install Python
        id: python-installer
        with:
          python-version: '3.8'

      - name: Chown for boost
        run: |
          sudo chown -R $USER:$USER /usr/local/include/
          sudo chown -R $USER:$USER /usr/local/lib/

      - name: ls
        run: ls -la
      - name: python version
        run: echo ${{ steps.python-installer.outputs.python-version }} 

      - name: Cache boost
        id: cache-boost
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/include/boost
            /usr/local/lib/cmake/boost_*
            /usr/local/lib/libboost_*
            /usr/local/lib/cmake/Boost*
          key: ${{ runner.os }}-boost-more-cache1

      - name: Pre-install boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          mkdir ~/boost &&
          wget -nv -O boost_1_76_0.tar.gz https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz &&
          tar xzf boost_1_76_0.tar.gz -C ~/boost && cd ~/boost/boost_1_76_0/ &&
          ./bootstrap.sh --with-python=/usr/bin/python3.8 --with-python-version=3.8 &&
          ./b2 -j `nproc` &&  sudo ./b2 install -j `nproc`

#      - name: ls
#        run: ls -la ~/boost/
#
#      - name: ls
#        run: ls -la ~/boost/boost_1_76_0
#
#      - name: Install boost
#        run: cd ~/boost/boost_1_76_0/ && sudo ./b2 install -j `nproc`

      - name: cmake and build
        run: |
          mkdir build
          cd build
          cmake ../
          cmake --build . -- -j 6
          cd ..
          python3 -m venv .venv
          . .venv/bin/activate
          pip3 install .
          pwd
          python3 ./test/test.py
#
#      - name: print hello
#        run: |
#          . .venv/bin/activate
#          python3 ./test/test.py
